### ISSUE TITLE
Go to next lab button error

### ISSUE THREAD

**Issue by jameskellynet** [nre-learning/antidote-web#26]
When on the Git lesson, the "Go to the next lab" button results in an error dialog box saying:

> _An error occurred.
> 
> Error with initial lesson request: Invalid stage ID for this lesson
> Unfortunately this means we can't show you this lesson right now. Please post the details of what lesson you were accessing, as well as the above error message as a Github issue. In the meantime, try refreshing this page, or trying another lesson._

Beyond this issue itself, there is a problem with the "Github issue" hyperlink in the dialog box that points to a github.com URL that 404s because the /nre-learning/ is missing from the URL.

**Comment by Mierdin** [comment]
Regarding the first issue, the button to go to the next lab shouldn't even be enabled if you're at the last one, so that shouldn't happen. Looks like when I committed https://github.com/nre-learning/antidote-web/commit/e4b0558ee80a5fc02e50feb6761766141eb2a374 I neglected to adjust the return value from `renderLessonStages()` accordingly.

Will fix that, as well as the broken github issue link and the error dialog problems.
